server:
  port: 8080
spring:
  profiles:
    active: dev
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${spring.ai.openai.api-key}
      chat:
        options:
          model: qwen3-235b-a22b

  application:
   name: BitGain
  datasource:
    url: jdbc:mysql://localhost:3306/bitgain?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  mail:
    host: smtp.qq.com
    port: 587
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.Lucius.entity
  configuration:
    map-underscore-to-camel-case: true
# JWT
psy:
  jwt:
    user-secret-key: ABELBeJAxH5EAzCdEZk3mLQKu8U0qsuE5WQ4CKc7dehesgsdgdsfrgresdgggggredfbgderghedrhbedEs=
    user-token-name: Authorization
    user-ttl: 7200000